version: '2'

services:
  rails:
    image: matheusmiranda/pokedez:latest
    build:
      context: .
      dockerfile: ./docker/rails-server/Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - rails-server-db
    command: bash -c "rm -rf tmp/ && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch.Dockerfile
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
