version: '2'

services:
  rails:
    build:
      context: .
      dockerfile: ./docker/rails-server/Dockerfile
    ports:
      - 3000:3000
    command: bash -c "rm -rf tmp/ && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch.Dockerfile
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
